name: Main

on:
  push:
    branches:
      - 'main'

jobs: 

  artifact: 
    name: Test main branch
    runs-on: ubuntu-18.04
    steps:
      - name: checkout 
        uses: actions/checkout@v2
      - name: Set-up node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        with:
          target_branch: gh-pages
          build_dir: build
            



  # steps:
  #   name: checkout
  #     uses: actions/checkout@v1
  #   - name: Set-up Node
  #     uses: actions/setup-node@v1
  #     with: 
  #       node-version: "10.x"

